- name: Checkmarx AST CLI Action
  uses: checkmarx/ast-github-action@main
  with:
    additional_params: --report-format sarif --output-path . ...

- name: Upload SARIF file
  uses: github/codeql-action/upload-sarif@v3
  with:
    sarif_file: cx_result.sarif
